### ISSUE TITLE
name 'rdmolfiles' is not defined

### ISSUE THREAD

**Issue by lxiongZ** [ZillaRU/molPropPred#1]
train_graph = [mol_to_bigraph(mol,
                              node_featurizer=atom_featurizer,
                              edge_featurizer=bond_featurizer) for mol in train_mols]
运行显示：NameError: name 'rdmolfiles' is not defined

想问下这个步骤到底如何解决 ？

**Comment by ZillaRU** [comment]
你可以pdb进去debug看下，应该是dgl-lifesci内部报错。我猜测是rdkit和dgl-lifesci两个包版本不兼容导致的，是这个原因的话检查下版本依赖。🤣不搞这东西好几年了都

**Comment by ZillaRU** [comment]
看下readme的caution部分 原来之前我解过这个bug。。。

**Comment by lxiongZ** [comment]
是的 我看到那个readme 但是不是很理解什么意思 就是我尝试了了直接利用txt配置环境 但是一直卡住 然后就自己安装所需的库 装了dgl0.4.2版本 rdkit装了一个2022的版本的 就是自己按照test_vis.ipynb这个文件进行一步步运行  到上面那一步就报错
好的 谢谢你的解答 ！

**Comment by ZillaRU** [comment]
还要安装matraj

**Comment by lxiongZ** [comment]
好的 因为安装matraj装了一个 https://visualstudio.microsoft.com/visual-cpp-build-tools/个这个 
之后重启电脑就运行没有那个报错了 也不知道是不是装了这个的原因 还是重启的原因😂
